import type { Metadata } from "next";
import { Inter } from "next/font/google";
import type { ReactNode } from "react";
import "./globals.css";
import styles from "./layout.module.css";
import {Nav} from "../components/Nav";
import {Footer} from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LUXECLUB - Your Journey | Our Signature",
  description: "Generated by create next app",
};

interface Props {
  readonly children: ReactNode;
}
export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* {children} */}
        <section className={styles.container}>
            <Nav />

            <header className={styles.header}>
            </header>

            <main className={styles.main}>{children}</main>

            <footer className={styles.footer}>

            </footer>
            <Footer />
          </section>
      </body>
    </html>
  );
}
