import type { Metadata } from "next";
import { Inter } from "next/font/google";
import type { ReactNode } from "react";
import "./globals.css";
import "./main.css";
import styles from "./layout.module.css";
import { Nav } from "../components/Nav";
import { Footer } from "../components/Footer";
import NextTopLoader from "nextjs-toploader";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LUXECLUB - Your Journey | Our Signature",
  description: "Generated by create next app",
};

interface Props {
  readonly children: ReactNode;
}
export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* {children} */}
        <NextTopLoader
          color="#DFA42E"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={false}
          easing="ease"
          speed={200}
          shadow="0 0 10px #DFA42E,0 0 5px #DFA42E"
        />
        <section className={styles.container}>
          <Nav />

          <header className={styles.header}></header>

          <main className={styles.main}>{children}</main>

          <footer className={styles.footer}></footer>
          <Footer />
        </section>
      </body>
    </html>
  );
}
